// 客机数据（按家族 / 子型号细分，含中英文）
const FAMILIES = [
  {
    "id": "b737",
    "name": "波音 737",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "窄体客机",
    "image": "images/b737-ng.jpg",
    "wiki": "https://baike.baidu.com/item/波音737",
    "desc": "波音 737 是世界上最畅销的民用客机系列，自 1967 年首飞以来衍生出多个世代，广泛服务于中短程航线。",
    "variants": [
      {
        "id": "b737-cl",
        "name": "波音 737 Classic",
        "sub": "737-300 / 400 / 500",
        "firstFlight": "1984",
        "seats": "126 - 149",
        "range": "约 3,500 - 4,200 km",
        "cruise": "856 km/h",
        "engines": "两台 CFM56-3 涡扇发动机",
        "wiki": "https://baike.baidu.com/item/波音737",
        "nameEn": "Boeing 737 Classic",
        "subEn": "737-300 / 400 / 500",
        "enginesEn": "Two CFM56-3 turbofan engines"
      },
      {
        "id": "b737-ng",
        "name": "波音 737 NG",
        "sub": "737-600 / 700 / 800 / 900",
        "firstFlight": "1997",
        "seats": "110 - 189",
        "range": "约 5,400 - 6,000 km",
        "cruise": "842 km/h",
        "engines": "两台 CFM56-7 涡扇发动机",
        "wiki": "https://baike.baidu.com/item/波音737",
        "nameEn": "Boeing 737 NG",
        "subEn": "737-600 / 700 / 800 / 900",
        "enginesEn": "Two CFM56-7 turbofan engines"
      },
      {
        "id": "b737-max",
        "name": "波音 737 MAX",
        "sub": "MAX 7 / 8 / 9",
        "firstFlight": "2016",
        "seats": "138 - 178",
        "range": "约 6,570 km",
        "cruise": "842 km/h",
        "engines": "两台 LEAP-1B 涡扇发动机",
        "wiki": "https://baike.baidu.com/item/波音737MAX",
        "nameEn": "Boeing 737 MAX",
        "subEn": "MAX 7 / 8 / 9",
        "enginesEn": "Two LEAP-1B turbofan engines"
      }
    ],
    "nameEn": "Boeing 737",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Narrow-body airliner",
    "descEn": "The Boeing 737 is the best-selling civil airliner family in history. Since its first flight in 1967 it has evolved through several generations and serves short- to medium-haul routes worldwide."
  },
  {
    "id": "b747",
    "name": "波音 747",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b747-8.jpg",
    "wiki": "https://baike.baidu.com/item/波音747",
    "desc": "波音 747 是首款宽体客机，因体型巨大被称为“珍宝客机”(Jumbo Jet)，长期是世界上最大的民用飞机。",
    "variants": [
      {
        "id": "b747-400",
        "name": "波音 747-400",
        "sub": "最受欢迎的二代型",
        "firstFlight": "1988",
        "seats": "416 - 660",
        "range": "约 13,450 km",
        "cruise": "920 km/h",
        "engines": "四台 CF6-80C2 / PW4000 / RB211 涡扇",
        "wiki": "https://baike.baidu.com/item/波音747",
        "nameEn": "Boeing 747-400",
        "subEn": "Most popular second-generation variant",
        "enginesEn": "Four CF6-80C2 / PW4000 / RB211 turbofans"
      },
      {
        "id": "b747-8",
        "name": "波音 747-8",
        "sub": "最新、最长型号",
        "firstFlight": "2010",
        "seats": "467",
        "range": "约 14,815 km",
        "cruise": "920 km/h",
        "engines": "四台 GEnx-2B 涡扇",
        "wiki": "https://baike.baidu.com/item/波音747",
        "nameEn": "Boeing 747-8",
        "subEn": "Newest and longest variant",
        "enginesEn": "Four GEnx-2B turbofans"
      }
    ],
    "nameEn": "Boeing 747",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "descEn": "The Boeing 747 was the first wide-body airliner. Nicknamed the 'Jumbo Jet' for its enormous size, it was long the world's largest civil aircraft."
  },
  {
    "id": "b757",
    "name": "波音 757",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "窄体客机",
    "image": "images/b757-300.jpg",
    "wiki": "https://baike.baidu.com/item/波音757",
    "desc": "波音 757 机身修长、推力强劲，特别适合高海拔与短跑道机场，主要执飞中程干线。",
    "variants": [
      {
        "id": "b757-200",
        "name": "波音 757-200",
        "sub": "标准型",
        "firstFlight": "1982",
        "seats": "200 - 228",
        "range": "约 7,270 km",
        "cruise": "871 km/h",
        "engines": "两台 RB211 / PW2000 涡扇",
        "wiki": "https://baike.baidu.com/item/波音757",
        "nameEn": "Boeing 757-200",
        "subEn": "Standard version",
        "enginesEn": "Two RB211 / PW2000 turbofans"
      },
      {
        "id": "b757-300",
        "name": "波音 757-300",
        "sub": "加长型",
        "firstFlight": "1996",
        "seats": "243 - 280",
        "range": "约 6,420 km",
        "cruise": "871 km/h",
        "engines": "两台 RB211-535E4 / PW2040 涡扇",
        "wiki": "https://baike.baidu.com/item/波音757",
        "nameEn": "Boeing 757-300",
        "subEn": "Stretched version",
        "enginesEn": "Two RB211-535E4 / PW2040 turbofans"
      }
    ],
    "nameEn": "Boeing 757",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Narrow-body airliner",
    "descEn": "The Boeing 757 has a slender fuselage and powerful engines, making it well suited to high-altitude and short-runway airports, mainly flying medium-haul trunk routes."
  },
  {
    "id": "b767",
    "name": "波音 767",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b767-passenger.jpg",
    "wiki": "https://baike.baidu.com/item/波音767",
    "desc": "波音 767 是双发宽体客机，采用两人制驾驶舱，广泛用于跨洋与高密度航线，并衍生出畅销货机。",
    "variants": [
      {
        "id": "b767-300er",
        "name": "波音 767-300ER",
        "sub": "最畅销的远程型",
        "firstFlight": "1986",
        "seats": "218 - 269",
        "range": "约 11,000 km",
        "cruise": "852 km/h",
        "engines": "两台 CF6-80C2 / PW4000 / RB211 涡扇",
        "wiki": "https://baike.baidu.com/item/波音767",
        "nameEn": "Boeing 767-300ER",
        "subEn": "Best-selling long-range variant",
        "enginesEn": "Two CF6-80C2 / PW4000 / RB211 turbofans"
      },
      {
        "id": "b767-400er",
        "name": "波音 767-400ER",
        "sub": "加长型",
        "firstFlight": "1999",
        "seats": "245 - 375",
        "range": "约 10,400 km",
        "cruise": "852 km/h",
        "engines": "两台 CF6-80C2 / PW4000 涡扇",
        "wiki": "https://baike.baidu.com/item/波音767",
        "nameEn": "Boeing 767-400ER",
        "subEn": "Stretched version",
        "enginesEn": "Two CF6-80C2 / PW4000 turbofans"
      }
    ],
    "nameEn": "Boeing 767",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "descEn": "The Boeing 767 is a twin-engine wide-body airliner with a two-pilot cockpit, widely used on transoceanic and high-density routes, and it spawned a popular freighter variant."
  },
  {
    "id": "b777",
    "name": "波音 777",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b777-200.jpg",
    "wiki": "https://baike.baidu.com/item/波音777",
    "desc": "波音 777 是世界上最大的双发宽体客机，远程巡航能力极强，是全球长途航线的主力之一。",
    "variants": [
      {
        "id": "b777-200",
        "name": "波音 777-200",
        "sub": "基本型",
        "firstFlight": "1994",
        "seats": "314",
        "range": "约 9,700 km",
        "cruise": "905 km/h",
        "engines": "两台 Trent 800 / GE90 / PW4000 涡扇",
        "wiki": "https://baike.baidu.com/item/波音777",
        "nameEn": "Boeing 777-200",
        "subEn": "Base version",
        "enginesEn": "Two Trent 800 / GE90 / PW4000 turbofans"
      },
      {
        "id": "b777-200er",
        "name": "波音 777-200ER",
        "sub": "增程型 (Extended Range)",
        "firstFlight": "1996",
        "seats": "314",
        "range": "约 14,260 km",
        "cruise": "905 km/h",
        "engines": "两台 Trent 800 / GE90 / PW4000 涡扇",
        "wiki": "https://baike.baidu.com/item/波音777",
        "nameEn": "Boeing 777-200ER",
        "subEn": "Extended Range version",
        "enginesEn": "Two Trent 800 / GE90 / PW4000 turbofans"
      },
      {
        "id": "b777-200lr",
        "name": "波音 777-200LR",
        "sub": "远程型 (Longer Range)",
        "firstFlight": "2005",
        "seats": "317",
        "range": "约 17,395 km",
        "cruise": "905 km/h",
        "engines": "两台 GE90-110B 涡扇",
        "wiki": "https://baike.baidu.com/item/波音777",
        "nameEn": "Boeing 777-200LR",
        "subEn": "Longer Range version",
        "enginesEn": "Two GE90-110B turbofans"
      },
      {
        "id": "b777-300er",
        "name": "波音 777-300ER",
        "sub": "加长增程型",
        "firstFlight": "2003",
        "seats": "365 - 396",
        "range": "约 13,649 km",
        "cruise": "905 km/h",
        "engines": "两台 GE90-115B 涡扇",
        "wiki": "https://baike.baidu.com/item/波音777",
        "nameEn": "Boeing 777-300ER",
        "subEn": "Stretched Extended Range",
        "enginesEn": "Two GE90-115B turbofans"
      }
    ],
    "nameEn": "Boeing 777",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "descEn": "The Boeing 777 is the world's largest twin-engine wide-body airliner, with exceptional long-range cruise capability and a backbone of global long-haul routes."
  },
  {
    "id": "b787",
    "name": "波音 787 梦想客机",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b787-9.jpg",
    "wiki": "https://baike.baidu.com/item/波音787",
    "desc": "波音 787 大量采用复合材料与电传操纵，强调燃油效率与乘坐舒适性，是面向 21 世纪的远程宽体主力。",
    "variants": [
      {
        "id": "b787-8",
        "name": "波音 787-8",
        "sub": "基本型",
        "firstFlight": "2009",
        "seats": "248",
        "range": "约 13,530 km",
        "cruise": "903 km/h",
        "engines": "两台 GEnx-1B / Trent 1000 涡扇",
        "wiki": "https://baike.baidu.com/item/波音787",
        "nameEn": "Boeing 787-8",
        "subEn": "Base version",
        "enginesEn": "Two GEnx-1B / Trent 1000 turbofans"
      },
      {
        "id": "b787-9",
        "name": "波音 787-9",
        "sub": "加长型",
        "firstFlight": "2013",
        "seats": "290",
        "range": "约 14,140 km",
        "cruise": "903 km/h",
        "engines": "两台 GEnx-1B / Trent 1000 涡扇",
        "wiki": "https://baike.baidu.com/item/波音787",
        "nameEn": "Boeing 787-9",
        "subEn": "Stretched version",
        "enginesEn": "Two GEnx-1B / Trent 1000 turbofans"
      },
      {
        "id": "b787-10",
        "name": "波音 787-10",
        "sub": "最大加长型",
        "firstFlight": "2017",
        "seats": "336",
        "range": "约 11,730 km",
        "cruise": "903 km/h",
        "engines": "两台 GEnx-1B 涡扇",
        "wiki": "https://baike.baidu.com/item/波音787",
        "nameEn": "Boeing 787-10",
        "subEn": "Largest stretched version",
        "enginesEn": "Two GEnx-1B turbofans"
      }
    ],
    "nameEn": "Boeing 787 Dreamliner",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "descEn": "The Boeing 787 makes extensive use of composite materials and fly-by-wire controls, emphasizing fuel efficiency and passenger comfort as a 21st-century long-range wide-body mainstay."
  },
  {
    "id": "a320",
    "name": "空客 A320 系列",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "窄体客机",
    "image": "images/a321.jpg",
    "wiki": "https://baike.baidu.com/item/空中客车A320",
    "desc": "空客 A320 系列是历史上最畅销的窄体客机，率先在民航引入电传操纵与侧杆，包含 A318/A319/A320/A321 等型号，并发展出 NEO（新型发动机选项）系列。",
    "variants": [
      {
        "id": "a318",
        "name": "空客 A318",
        "sub": "A318-100（最小成员）",
        "firstFlight": "2002",
        "seats": "107 - 132",
        "range": "约 5,950 km",
        "cruise": "830 km/h",
        "engines": "两台 CFM56-5B / PW6000 涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A318",
        "nameEn": "Airbus A318",
        "subEn": "A318-100 (smallest member)",
        "enginesEn": "Two CFM56-5B / PW6000 turbofans"
      },
      {
        "id": "a319",
        "name": "空客 A319",
        "sub": "A319-100 / A319neo",
        "firstFlight": "1995",
        "seats": "124 - 156",
        "range": "约 6,850 km",
        "cruise": "830 km/h",
        "engines": "两台 CFM56-5B / V2500 / LEAP-1A 涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A319",
        "nameEn": "Airbus A319",
        "subEn": "A319-100 / A319neo",
        "enginesEn": "Two CFM56-5B / V2500 / LEAP-1A turbofans"
      },
      {
        "id": "a320",
        "name": "空客 A320",
        "sub": "A320-200 / A320neo",
        "firstFlight": "1987",
        "seats": "150 - 186",
        "range": "约 6,100 km",
        "cruise": "830 km/h",
        "engines": "两台 CFM56-5B / V2500 / LEAP-1A 涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A320",
        "nameEn": "Airbus A320",
        "subEn": "A320-200 / A320neo",
        "enginesEn": "Two CFM56-5B / V2500 / LEAP-1A turbofans"
      },
      {
        "id": "a321",
        "name": "空客 A321",
        "sub": "A321-200 / A321neo / A321XLR",
        "firstFlight": "1993",
        "seats": "185 - 244",
        "range": "约 7,400 km（XLR 约 8,700 km）",
        "cruise": "830 km/h",
        "engines": "两台 CFM56-5B / V2500 / LEAP-1A 涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A321",
        "nameEn": "Airbus A321",
        "subEn": "A321-200 / A321neo / A321XLR",
        "enginesEn": "Two CFM56-5B / V2500 / LEAP-1A turbofans"
      }
    ],
    "nameEn": "Airbus A320 family",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Narrow-body airliner",
    "descEn": "The Airbus A320 family is the best-selling narrow-body airliner in history, the first to introduce fly-by-wire and sidesticks in civil aviation, comprising the A318/A319/A320/A321 and the NEO (New Engine Option) variants."
  },
  {
    "id": "a330",
    "name": "空客 A330",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "宽体客机",
    "image": "images/a330neo.jpg",
    "wiki": "https://baike.baidu.com/item/空中客车A330",
    "desc": "空客 A330 是双发宽体客机，以高经济性与可靠性著称，是中远程航线的常见机型，并发展出 A330neo 系列。",
    "variants": [
      {
        "id": "a330-200",
        "name": "空客 A330-200",
        "sub": "标准型",
        "firstFlight": "1997",
        "seats": "246 - 300",
        "range": "约 13,400 km",
        "cruise": "871 km/h",
        "engines": "两台 Trent 700 / CF6 / PW4000 涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A330",
        "nameEn": "Airbus A330-200",
        "subEn": "Standard version",
        "enginesEn": "Two Trent 700 / CF6 / PW4000 turbofans"
      },
      {
        "id": "a330-300",
        "name": "空客 A330-300",
        "sub": "加长型",
        "firstFlight": "1993",
        "seats": "300 - 440",
        "range": "约 11,750 km",
        "cruise": "871 km/h",
        "engines": "两台 Trent 700 / CF6 / PW4000 涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A330",
        "nameEn": "Airbus A330-300",
        "subEn": "Stretched version",
        "enginesEn": "Two Trent 700 / CF6 / PW4000 turbofans"
      },
      {
        "id": "a330neo",
        "name": "空客 A330neo",
        "sub": "A330-800 / A330-900",
        "firstFlight": "2014",
        "seats": "260 - 460",
        "range": "约 13,900 km",
        "cruise": "871 km/h",
        "engines": "两台 Rolls-Royce Trent 7000 涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A330",
        "nameEn": "Airbus A330neo",
        "subEn": "A330-800 / A330-900",
        "enginesEn": "Two Rolls-Royce Trent 7000 turbofans"
      }
    ],
    "nameEn": "Airbus A330",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Wide-body airliner",
    "descEn": "The Airbus A330 is a twin-engine wide-body airliner known for its economy and reliability on medium- to long-haul routes, later developed into the A330neo family."
  },
  {
    "id": "a350",
    "name": "空客 A350",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "宽体客机",
    "image": "images/a350-900.jpg",
    "wiki": "https://baike.baidu.com/item/空中客车A350",
    "desc": "空客 A350 是全新设计的宽体客机(XWB)，大量使用碳纤维复合材料，主打超远航程与低油耗。",
    "variants": [
      {
        "id": "a350-900",
        "name": "空客 A350-900",
        "sub": "基本型",
        "firstFlight": "2013",
        "seats": "300 - 350",
        "range": "约 15,000 km",
        "cruise": "905 km/h",
        "engines": "两台 Rolls-Royce Trent XWB-84 涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A350",
        "nameEn": "Airbus A350-900",
        "subEn": "Base version",
        "enginesEn": "Two Rolls-Royce Trent XWB-84 turbofans"
      },
      {
        "id": "a350-1000",
        "name": "空客 A350-1000",
        "sub": "加长型",
        "firstFlight": "2016",
        "seats": "350 - 410",
        "range": "约 16,100 km",
        "cruise": "905 km/h",
        "engines": "两台 Rolls-Royce Trent XWB-97 涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A350",
        "nameEn": "Airbus A350-1000",
        "subEn": "Stretched version",
        "enginesEn": "Two Rolls-Royce Trent XWB-97 turbofans"
      }
    ],
    "nameEn": "Airbus A350",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Wide-body airliner",
    "descEn": "The Airbus A350 is an all-new wide-body airliner (XWB) using extensive carbon-fibre composites, built for ultra-long range and low fuel burn."
  },
  {
    "id": "a380",
    "name": "空客 A380",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "宽体客机",
    "image": "images/a380-800.jpg",
    "wiki": "https://baike.baidu.com/item/空中客车A380",
    "desc": "空客 A380 是世界上最大的客机，也是唯一的全双层喷气式客机，四发超宽体布局提供无与伦比的载客量。",
    "variants": [
      {
        "id": "a380-800",
        "name": "空客 A380-800",
        "sub": "唯一量产型",
        "firstFlight": "2005",
        "seats": "525 - 853",
        "range": "约 15,200 km",
        "cruise": "920 km/h",
        "engines": "四台 GP7200 / Trent 900 涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A380",
        "nameEn": "Airbus A380-800",
        "subEn": "Only production variant",
        "enginesEn": "Four GP7200 / Trent 900 turbofans"
      }
    ],
    "nameEn": "Airbus A380",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Wide-body airliner",
    "descEn": "The Airbus A380 is the world's largest passenger aircraft and the only full double-deck jetliner, with a four-engine ultra-wide layout offering unmatched capacity."
  },
  {
    "id": "a220",
    "name": "空客 A220",
    "manufacturer": "空客 (Airbus)",
    "country": "加拿大",
    "category": "窄体客机",
    "image": "images/a220-100.jpg",
    "wiki": "https://baike.baidu.com/item/空中客车A220",
    "desc": "空客 A220 最初由庞巴迪以 CSeries 名义研制，后被空客收购，专为 100-150 座市场设计，燃油效率出众。",
    "variants": [
      {
        "id": "a220-100",
        "name": "空客 A220-100",
        "sub": "原 CS100",
        "firstFlight": "2013",
        "seats": "100 - 135",
        "range": "约 6,300 km",
        "cruise": "871 km/h",
        "engines": "两台 Pratt & Whitney PW1500G 齿轮传动涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A220",
        "nameEn": "Airbus A220-100",
        "subEn": "Formerly CS100",
        "enginesEn": "Two Pratt & Whitney PW1500G geared turbofans"
      },
      {
        "id": "a220-300",
        "name": "空客 A220-300",
        "sub": "原 CS300（加长型）",
        "firstFlight": "2015",
        "seats": "130 - 160",
        "range": "约 5,950 km",
        "cruise": "871 km/h",
        "engines": "两台 Pratt & Whitney PW1500G 齿轮传动涡扇",
        "wiki": "https://baike.baidu.com/item/空中客车A220",
        "nameEn": "Airbus A220-300",
        "subEn": "Formerly CS300 (stretched)",
        "enginesEn": "Two Pratt & Whitney PW1500G geared turbofans"
      }
    ],
    "nameEn": "Airbus A220",
    "manufacturerEn": "Airbus",
    "countryEn": "Canada",
    "categoryEn": "Narrow-body airliner",
    "descEn": "The Airbus A220 was originally developed by Bombardier as the CSeries and later acquired by Airbus, designed for the 100-150 seat market with outstanding fuel efficiency."
  },
  {
    "id": "ejet",
    "name": "巴航工业 E-Jet",
    "manufacturer": "巴航工业 (Embraer)",
    "country": "巴西",
    "category": "支线客机",
    "image": "images/e170.jpg",
    "wiki": "https://baike.baidu.com/item/巴航工业E系列",
    "desc": "巴航工业 E-Jet 系列是巴西航空工业公司研制的中小型支线喷气客机，兼顾经济性与舒适性。",
    "variants": [
      {
        "id": "e170",
        "name": "巴航 E170",
        "sub": "最小成员",
        "firstFlight": "2002",
        "seats": "66 - 80",
        "range": "约 3,890 km",
        "cruise": "850 km/h",
        "engines": "两台 CF34-8E 涡扇",
        "wiki": "https://baike.baidu.com/item/巴航工业E系列",
        "nameEn": "Embraer E170",
        "subEn": "Smallest member",
        "enginesEn": "Two CF34-8E turbofans"
      },
      {
        "id": "e190",
        "name": "巴航 E190",
        "sub": "最受欢迎型号",
        "firstFlight": "2004",
        "seats": "96 - 114",
        "range": "约 4,537 km",
        "cruise": "850 km/h",
        "engines": "两台 CF34-10E 涡扇",
        "wiki": "https://baike.baidu.com/item/巴航工业E系列",
        "nameEn": "Embraer E190",
        "subEn": "Most popular variant",
        "enginesEn": "Two CF34-10E turbofans"
      },
      {
        "id": "e195e2",
        "name": "巴航 E195-E2",
        "sub": "E2 新一代",
        "firstFlight": "2016",
        "seats": "120 - 146",
        "range": "约 4,815 km",
        "cruise": "850 km/h",
        "engines": "两台 Pratt & Whitney PW1900G 齿轮传动涡扇",
        "wiki": "https://baike.baidu.com/item/巴航工业E-Jet_E2",
        "nameEn": "Embraer E195-E2",
        "subEn": "New-generation E2",
        "enginesEn": "Two Pratt & Whitney PW1900G geared turbofans"
      }
    ],
    "nameEn": "Embraer E-Jet",
    "manufacturerEn": "Embraer",
    "countryEn": "Brazil",
    "categoryEn": "Regional jet",
    "descEn": "The Embraer E-Jet family is a range of small-to-medium regional jets from Embraer, balancing economy and comfort."
  },
  {
    "id": "crj",
    "name": "庞巴迪 CRJ",
    "manufacturer": "庞巴迪 (Bombardier)",
    "country": "加拿大",
    "category": "支线客机",
    "image": "images/crj700.jpg",
    "wiki": "https://baike.baidu.com/item/庞巴迪CRJ",
    "desc": "庞巴迪 CRJ 系列是全球最成功的支线喷气客机之一，后由三菱重工收购，主要服务于低密度支线航线。",
    "variants": [
      {
        "id": "crj700",
        "name": "庞巴迪 CRJ700",
        "sub": "标准型",
        "firstFlight": "1999",
        "seats": "66 - 78",
        "range": "约 2,350 km",
        "cruise": "860 km/h",
        "engines": "两台 CF34-8C 涡扇",
        "wiki": "https://baike.baidu.com/item/庞巴迪CRJ",
        "nameEn": "Bombardier CRJ700",
        "subEn": "Standard version",
        "enginesEn": "Two CF34-8C turbofans"
      },
      {
        "id": "crj900",
        "name": "庞巴迪 CRJ900",
        "sub": "加长型",
        "firstFlight": "2001",
        "seats": "72 - 100",
        "range": "约 2,950 km",
        "cruise": "860 km/h",
        "engines": "两台 CF34-8C5 涡扇",
        "wiki": "https://baike.baidu.com/item/庞巴迪CRJ",
        "nameEn": "Bombardier CRJ900",
        "subEn": "Stretched version",
        "enginesEn": "Two CF34-8C5 turbofans"
      },
      {
        "id": "crj1000",
        "name": "庞巴迪 CRJ1000",
        "sub": "最大加长型",
        "firstFlight": "2009",
        "seats": "97 - 104",
        "range": "约 2,780 km",
        "cruise": "860 km/h",
        "engines": "两台 CF34-8C5 涡扇",
        "wiki": "https://baike.baidu.com/item/庞巴迪CRJ",
        "nameEn": "Bombardier CRJ1000",
        "subEn": "Largest stretched version",
        "enginesEn": "Two CF34-8C5 turbofans"
      }
    ],
    "nameEn": "Bombardier CRJ",
    "manufacturerEn": "Bombardier",
    "countryEn": "Canada",
    "categoryEn": "Regional jet",
    "descEn": "The Bombardier CRJ series is among the most successful regional jets ever, later acquired by Mitsubishi Heavy Industries, serving low-density regional routes."
  },
  {
    "id": "atr72",
    "name": "ATR 72",
    "manufacturer": "ATR",
    "country": "法国 / 意大利",
    "category": "涡桨客机",
    "image": "images/atr72-600.jpg",
    "wiki": "https://baike.baidu.com/item/ATR72",
    "desc": "ATR 72 是法国与意大利合资公司 ATR 研制的双发涡桨支线客机，以低油耗适合短途低密度航线。",
    "variants": [
      {
        "id": "atr72-600",
        "name": "ATR 72-600",
        "sub": "最新量产型",
        "firstFlight": "2009",
        "seats": "68 - 78",
        "range": "约 1,528 km",
        "cruise": "509 km/h",
        "engines": "两台 PW127M 涡桨发动机",
        "wiki": "https://baike.baidu.com/item/ATR72",
        "nameEn": "ATR 72-600",
        "subEn": "Latest production variant",
        "enginesEn": "Two PW127M turboprop engines"
      }
    ],
    "nameEn": "ATR 72",
    "manufacturerEn": "ATR",
    "countryEn": "France / Italy",
    "categoryEn": "Turboprop airliner",
    "descEn": "The ATR 72 is a twin-engine turboprop regional airliner from the French-Italian joint venture ATR, fuel-efficient for short, low-density routes."
  },
  {
    "id": "c919",
    "name": "中国商飞 C919",
    "manufacturer": "中国商飞 (Comac)",
    "country": "中国",
    "category": "窄体客机",
    "image": "images/c919.jpg",
    "wiki": "https://baike.baidu.com/item/C919",
    "desc": "C919 是中国商飞研制的中程窄体客机，于 2008 年立项，对标空客 A320 与波音 737，是中国首款按国际适航标准研制的干线客机。",
    "variants": [
      {
        "id": "c919",
        "name": "中国商飞 C919",
        "sub": "标准型",
        "firstFlight": "2017",
        "seats": "158 - 192",
        "range": "约 5,555 km",
        "cruise": "834 km/h",
        "engines": "两台 LEAP-1C 涡扇发动机",
        "wiki": "https://baike.baidu.com/item/C919",
        "nameEn": "Comac C919",
        "subEn": "Standard version",
        "enginesEn": "Two LEAP-1C turbofan engines"
      }
    ],
    "nameEn": "Comac C919",
    "manufacturerEn": "Comac",
    "countryEn": "China",
    "categoryEn": "Narrow-body airliner",
    "descEn": "The Comac C919 is a medium-range narrow-body airliner developed by Comac, launched in 2008 to compete with the Airbus A320 and Boeing 737, and China's first trunk airliner built to international airworthiness standards."
  },
  {
    "id": "md",
    "name": "麦道 MD 系列",
    "manufacturer": "麦道 (McDonnell Douglas)",
    "country": "美国",
    "category": "窄体客机",
    "image": "images/md90.jpg",
    "wiki": "https://baike.baidu.com/item/麦克唐纳-道格拉斯MD-80",
    "desc": "麦道 MD 系列是基于 DC-9 发展的单通道客机，采用尾吊双发布局，曾是上世纪 80-90 年代美国国内航线的主力之一。",
    "variants": [
      {
        "id": "md80",
        "name": "麦道 MD-80",
        "sub": "MD-82 / MD-83 等",
        "firstFlight": "1979",
        "seats": "130 - 172",
        "range": "约 3,600 km",
        "cruise": "811 km/h",
        "engines": "两台 Pratt & Whitney JT8D-200 涡扇",
        "wiki": "https://baike.baidu.com/item/麦克唐纳-道格拉斯MD-80",
        "nameEn": "McDonnell Douglas MD-80",
        "subEn": "MD-82 / MD-83 etc.",
        "enginesEn": "Two Pratt & Whitney JT8D-200 turbofans"
      },
      {
        "id": "md90",
        "name": "麦道 MD-90",
        "sub": "放大型",
        "firstFlight": "1993",
        "seats": "153 - 172",
        "range": "约 3,860 km",
        "cruise": "811 km/h",
        "engines": "两台 IAE V2525-D5 涡扇",
        "wiki": "https://baike.baidu.com/item/麦克唐纳-道格拉斯MD-90",
        "nameEn": "McDonnell Douglas MD-90",
        "subEn": "Enlarged version",
        "enginesEn": "Two IAE V2525-D5 turbofans"
      }
    ],
    "nameEn": "McDonnell Douglas MD series",
    "manufacturerEn": "McDonnell Douglas",
    "countryEn": "USA",
    "categoryEn": "Narrow-body airliner",
    "descEn": "The McDonnell Douglas MD series is a single-aisle airliner developed from the DC-9 with a rear-mounted twin-engine layout, a mainstay of US domestic routes in the 1980s-90s."
  },
  {
    "id": "mdd-wide",
    "name": "麦道 DC-10 / MD-11",
    "manufacturer": "麦道 (McDonnell Douglas)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/dc10.jpg",
    "wiki": "https://baike.baidu.com/item/DC-10",
    "desc": "麦道 DC-10 与 MD-11 是三发宽体客机，采用尾部第三发动机布局，曾广泛服务于跨洋航线与货运市场。DC-10 于 1970 年代首飞，MD-11 为其加长改进型，航程与燃油效率大幅提升。中国东方航空曾运营 MD-11 客货型号。",
    "variants": [
      {
        "id": "dc10",
        "name": "麦道 DC-10",
        "sub": "DC-10-10 / -30 / -40",
        "firstFlight": "1970",
        "seats": "250 - 380",
        "range": "约 9,600 - 12,000 km",
        "cruise": "908 km/h",
        "engines": "三台 GE CF6 / PW JT9D / RR RB211 涡扇",
        "wiki": "https://baike.baidu.com/item/DC-10",
        "nameEn": "McDonnell Douglas DC-10",
        "subEn": "DC-10-10 / -30 / -40",
        "enginesEn": "Three GE CF6 / PW JT9D / RR RB211 turbofans"
      },
      {
        "id": "md11",
        "name": "麦道 MD-11",
        "sub": "DC-10 加长改进型",
        "firstFlight": "1990",
        "seats": "285 - 410",
        "range": "约 12,700 km",
        "cruise": "945 km/h",
        "engines": "三台 GE CF6-80C2 / PW4000 涡扇",
        "wiki": "https://baike.baidu.com/item/MD-11",
        "nameEn": "McDonnell Douglas MD-11",
        "subEn": "Stretched DC-10 derivative",
        "enginesEn": "Three GE CF6-80C2 / PW4000 turbofans"
      }
    ],
    "nameEn": "McDonnell Douglas DC-10 / MD-11",
    "manufacturerEn": "McDonnell Douglas",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "descEn": "The McDonnell Douglas DC-10 and MD-11 are wide-body trijet airliners featuring a tail-mounted third engine. They served transoceanic routes and cargo markets worldwide. The DC-10 first flew in the 1970s; the MD-11 is a stretched derivative with significantly improved range and fuel efficiency. China Eastern Airlines operated both passenger and freighter MD-11s."
  },
  {
    "id": "c909",
    "name": "中国商飞 C909",
    "manufacturer": "中国商飞 (Comac)",
    "country": "中国",
    "category": "支线客机",
    "image": "images/c909.jpg",
    "wiki": "https://baike.baidu.com/item/ARJ21",
    "desc": "C909 是中国商飞研制的支线喷气客机，前身为 ARJ21（21 世纪新一代支线飞机）。采用尾吊双发布局，2008 年首飞，是中国首款拥有自主知识产权的涡扇支线客机；2024 年起以 C909 品牌运营。",
    "variants": [
      {
        "id": "c909-700",
        "name": "中国商飞 C909（标准型）",
        "sub": "ARJ21-700",
        "firstFlight": "2008",
        "seats": "78 - 105",
        "range": "约 3,700 km",
        "cruise": "830 km/h",
        "engines": "两台 CF34-10A 涡扇发动机",
        "wiki": "https://baike.baidu.com/item/ARJ21",
        "nameEn": "Comac C909 (standard)",
        "subEn": "ARJ21-700",
        "enginesEn": "Two CF34-10A turbofan engines"
      },
      {
        "id": "c909-900",
        "name": "中国商飞 C909（加长型）",
        "sub": "ARJ21-900（规划中）",
        "firstFlight": "—",
        "seats": "约 105 - 115",
        "range": "约 3,300 km",
        "cruise": "830 km/h",
        "engines": "两台 CF34-10A 涡扇发动机",
        "wiki": "https://baike.baidu.com/item/ARJ21",
        "nameEn": "Comac C909 (stretched)",
        "subEn": "ARJ21-900 (planned)",
        "enginesEn": "Two CF34-10A turbofan engines"
      }
    ],
    "nameEn": "Comac C909",
    "manufacturerEn": "Comac",
    "countryEn": "China",
    "categoryEn": "Regional jet",
    "descEn": "The Comac C909 is a regional jet airliner developed by Comac, formerly known as the ARJ21 (Advanced Regional Jet). With a rear-mounted twin-engine layout, it first flew in 2008 and is China's first indigenously developed turbofan regional airliner; it has been marketed under the C909 brand since 2024."
  }
];

const AIRCRAFT = [
  {
    "familyId": "b737",
    "familyName": "波音 737",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "窄体客机",
    "image": "images/b737-cl.jpg",
    "familyDesc": "波音 737 是世界上最畅销的民用客机系列，自 1967 年首飞以来衍生出多个世代，广泛服务于中短程航线。",
    "familyWiki": "https://baike.baidu.com/item/波音737",
    "id": "b737-cl",
    "name": "波音 737 Classic",
    "sub": "737-300 / 400 / 500",
    "firstFlight": "1984",
    "seats": "126 - 149",
    "range": "约 3,500 - 4,200 km",
    "cruise": "856 km/h",
    "engines": "两台 CFM56-3 涡扇发动机",
    "wiki": "https://baike.baidu.com/item/波音737",
    "nameEn": "Boeing 737 Classic",
    "subEn": "737-300 / 400 / 500",
    "enginesEn": "Two CFM56-3 turbofan engines",
    "familyNameEn": "Boeing 737",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Boeing 737 is the best-selling civil airliner family in history. Since its first flight in 1967 it has evolved through several generations and serves short- to medium-haul routes worldwide."
  },
  {
    "familyId": "b737",
    "familyName": "波音 737",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "窄体客机",
    "image": "images/b737-ng.jpg",
    "familyDesc": "波音 737 是世界上最畅销的民用客机系列，自 1967 年首飞以来衍生出多个世代，广泛服务于中短程航线。",
    "familyWiki": "https://baike.baidu.com/item/波音737",
    "id": "b737-ng",
    "name": "波音 737 NG",
    "sub": "737-600 / 700 / 800 / 900",
    "firstFlight": "1997",
    "seats": "110 - 189",
    "range": "约 5,400 - 6,000 km",
    "cruise": "842 km/h",
    "engines": "两台 CFM56-7 涡扇发动机",
    "wiki": "https://baike.baidu.com/item/波音737",
    "nameEn": "Boeing 737 NG",
    "subEn": "737-600 / 700 / 800 / 900",
    "enginesEn": "Two CFM56-7 turbofan engines",
    "familyNameEn": "Boeing 737",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Boeing 737 is the best-selling civil airliner family in history. Since its first flight in 1967 it has evolved through several generations and serves short- to medium-haul routes worldwide."
  },
  {
    "familyId": "b737",
    "familyName": "波音 737",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "窄体客机",
    "image": "images/b737-max.jpg",
    "familyDesc": "波音 737 是世界上最畅销的民用客机系列，自 1967 年首飞以来衍生出多个世代，广泛服务于中短程航线。",
    "familyWiki": "https://baike.baidu.com/item/波音737",
    "id": "b737-max",
    "name": "波音 737 MAX",
    "sub": "MAX 7 / 8 / 9",
    "firstFlight": "2016",
    "seats": "138 - 178",
    "range": "约 6,570 km",
    "cruise": "842 km/h",
    "engines": "两台 LEAP-1B 涡扇发动机",
    "wiki": "https://baike.baidu.com/item/波音737MAX",
    "nameEn": "Boeing 737 MAX",
    "subEn": "MAX 7 / 8 / 9",
    "enginesEn": "Two LEAP-1B turbofan engines",
    "familyNameEn": "Boeing 737",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Boeing 737 is the best-selling civil airliner family in history. Since its first flight in 1967 it has evolved through several generations and serves short- to medium-haul routes worldwide."
  },
  {
    "familyId": "b747",
    "familyName": "波音 747",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b747-400.jpg",
    "familyDesc": "波音 747 是首款宽体客机，因体型巨大被称为“珍宝客机”(Jumbo Jet)，长期是世界上最大的民用飞机。",
    "familyWiki": "https://baike.baidu.com/item/波音747",
    "id": "b747-400",
    "name": "波音 747-400",
    "sub": "最受欢迎的二代型",
    "firstFlight": "1988",
    "seats": "416 - 660",
    "range": "约 13,450 km",
    "cruise": "920 km/h",
    "engines": "四台 CF6-80C2 / PW4000 / RB211 涡扇",
    "wiki": "https://baike.baidu.com/item/波音747",
    "nameEn": "Boeing 747-400",
    "subEn": "Most popular second-generation variant",
    "enginesEn": "Four CF6-80C2 / PW4000 / RB211 turbofans",
    "familyNameEn": "Boeing 747",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Boeing 747 was the first wide-body airliner. Nicknamed the 'Jumbo Jet' for its enormous size, it was long the world's largest civil aircraft."
  },
  {
    "familyId": "b747",
    "familyName": "波音 747",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b747-8.jpg",
    "familyDesc": "波音 747 是首款宽体客机，因体型巨大被称为“珍宝客机”(Jumbo Jet)，长期是世界上最大的民用飞机。",
    "familyWiki": "https://baike.baidu.com/item/波音747",
    "id": "b747-8",
    "name": "波音 747-8",
    "sub": "最新、最长型号",
    "firstFlight": "2010",
    "seats": "467",
    "range": "约 14,815 km",
    "cruise": "920 km/h",
    "engines": "四台 GEnx-2B 涡扇",
    "wiki": "https://baike.baidu.com/item/波音747",
    "nameEn": "Boeing 747-8",
    "subEn": "Newest and longest variant",
    "enginesEn": "Four GEnx-2B turbofans",
    "familyNameEn": "Boeing 747",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Boeing 747 was the first wide-body airliner. Nicknamed the 'Jumbo Jet' for its enormous size, it was long the world's largest civil aircraft."
  },
  {
    "familyId": "b757",
    "familyName": "波音 757",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "窄体客机",
    "image": "images/b757-200.jpg",
    "familyDesc": "波音 757 机身修长、推力强劲，特别适合高海拔与短跑道机场，主要执飞中程干线。",
    "familyWiki": "https://baike.baidu.com/item/波音757",
    "id": "b757-200",
    "name": "波音 757-200",
    "sub": "标准型",
    "firstFlight": "1982",
    "seats": "200 - 228",
    "range": "约 7,270 km",
    "cruise": "871 km/h",
    "engines": "两台 RB211 / PW2000 涡扇",
    "wiki": "https://baike.baidu.com/item/波音757",
    "nameEn": "Boeing 757-200",
    "subEn": "Standard version",
    "enginesEn": "Two RB211 / PW2000 turbofans",
    "familyNameEn": "Boeing 757",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Boeing 757 has a slender fuselage and powerful engines, making it well suited to high-altitude and short-runway airports, mainly flying medium-haul trunk routes."
  },
  {
    "familyId": "b757",
    "familyName": "波音 757",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "窄体客机",
    "image": "images/b757-300.jpg",
    "familyDesc": "波音 757 机身修长、推力强劲，特别适合高海拔与短跑道机场，主要执飞中程干线。",
    "familyWiki": "https://baike.baidu.com/item/波音757",
    "id": "b757-300",
    "name": "波音 757-300",
    "sub": "加长型",
    "firstFlight": "1996",
    "seats": "243 - 280",
    "range": "约 6,420 km",
    "cruise": "871 km/h",
    "engines": "两台 RB211-535E4 / PW2040 涡扇",
    "wiki": "https://baike.baidu.com/item/波音757",
    "nameEn": "Boeing 757-300",
    "subEn": "Stretched version",
    "enginesEn": "Two RB211-535E4 / PW2040 turbofans",
    "familyNameEn": "Boeing 757",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Boeing 757 has a slender fuselage and powerful engines, making it well suited to high-altitude and short-runway airports, mainly flying medium-haul trunk routes."
  },
  {
    "familyId": "b767",
    "familyName": "波音 767",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b767-passenger.jpg",
    "familyDesc": "波音 767 是双发宽体客机，采用两人制驾驶舱，广泛用于跨洋与高密度航线，并衍生出畅销货机。",
    "familyWiki": "https://baike.baidu.com/item/波音767",
    "id": "b767-300er",
    "name": "波音 767-300ER",
    "sub": "最畅销的远程型",
    "firstFlight": "1986",
    "seats": "218 - 269",
    "range": "约 11,000 km",
    "cruise": "852 km/h",
    "engines": "两台 CF6-80C2 / PW4000 / RB211 涡扇",
    "wiki": "https://baike.baidu.com/item/波音767",
    "nameEn": "Boeing 767-300ER",
    "subEn": "Best-selling long-range variant",
    "enginesEn": "Two CF6-80C2 / PW4000 / RB211 turbofans",
    "familyNameEn": "Boeing 767",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Boeing 767 is a twin-engine wide-body airliner with a two-pilot cockpit, widely used on transoceanic and high-density routes, and it spawned a popular freighter variant."
  },
  {
    "familyId": "b767",
    "familyName": "波音 767",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b767-passenger.jpg",
    "familyDesc": "波音 767 是双发宽体客机，采用两人制驾驶舱，广泛用于跨洋与高密度航线，并衍生出畅销货机。",
    "familyWiki": "https://baike.baidu.com/item/波音767",
    "id": "b767-400er",
    "name": "波音 767-400ER",
    "sub": "加长型",
    "firstFlight": "1999",
    "seats": "245 - 375",
    "range": "约 10,400 km",
    "cruise": "852 km/h",
    "engines": "两台 CF6-80C2 / PW4000 涡扇",
    "wiki": "https://baike.baidu.com/item/波音767",
    "nameEn": "Boeing 767-400ER",
    "subEn": "Stretched version",
    "enginesEn": "Two CF6-80C2 / PW4000 turbofans",
    "familyNameEn": "Boeing 767",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Boeing 767 is a twin-engine wide-body airliner with a two-pilot cockpit, widely used on transoceanic and high-density routes, and it spawned a popular freighter variant."
  },
  {
    "familyId": "b777",
    "familyName": "波音 777",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b777-200.jpg",
    "familyDesc": "波音 777 是世界上最大的双发宽体客机，远程巡航能力极强，是全球长途航线的主力之一。",
    "familyWiki": "https://baike.baidu.com/item/波音777",
    "id": "b777-200",
    "name": "波音 777-200",
    "sub": "基本型",
    "firstFlight": "1994",
    "seats": "314",
    "range": "约 9,700 km",
    "cruise": "905 km/h",
    "engines": "两台 Trent 800 / GE90 / PW4000 涡扇",
    "wiki": "https://baike.baidu.com/item/波音777",
    "nameEn": "Boeing 777-200",
    "subEn": "Base version",
    "enginesEn": "Two Trent 800 / GE90 / PW4000 turbofans",
    "familyNameEn": "Boeing 777",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Boeing 777 is the world's largest twin-engine wide-body airliner, with exceptional long-range cruise capability and a backbone of global long-haul routes."
  },
  {
    "familyId": "b777",
    "familyName": "波音 777",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b777-200er.jpg",
    "familyDesc": "波音 777 是世界上最大的双发宽体客机，远程巡航能力极强，是全球长途航线的主力之一。",
    "familyWiki": "https://baike.baidu.com/item/波音777",
    "id": "b777-200er",
    "name": "波音 777-200ER",
    "sub": "增程型 (Extended Range)",
    "firstFlight": "1996",
    "seats": "314",
    "range": "约 14,260 km",
    "cruise": "905 km/h",
    "engines": "两台 Trent 800 / GE90 / PW4000 涡扇",
    "wiki": "https://baike.baidu.com/item/波音777",
    "nameEn": "Boeing 777-200ER",
    "subEn": "Extended Range version",
    "enginesEn": "Two Trent 800 / GE90 / PW4000 turbofans",
    "familyNameEn": "Boeing 777",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Boeing 777 is the world's largest twin-engine wide-body airliner, with exceptional long-range cruise capability and a backbone of global long-haul routes."
  },
  {
    "familyId": "b777",
    "familyName": "波音 777",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b777-200lr.jpg",
    "familyDesc": "波音 777 是世界上最大的双发宽体客机，远程巡航能力极强，是全球长途航线的主力之一。",
    "familyWiki": "https://baike.baidu.com/item/波音777",
    "id": "b777-200lr",
    "name": "波音 777-200LR",
    "sub": "远程型 (Longer Range)",
    "firstFlight": "2005",
    "seats": "317",
    "range": "约 17,395 km",
    "cruise": "905 km/h",
    "engines": "两台 GE90-110B 涡扇",
    "wiki": "https://baike.baidu.com/item/波音777",
    "nameEn": "Boeing 777-200LR",
    "subEn": "Longer Range version",
    "enginesEn": "Two GE90-110B turbofans",
    "familyNameEn": "Boeing 777",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Boeing 777 is the world's largest twin-engine wide-body airliner, with exceptional long-range cruise capability and a backbone of global long-haul routes."
  },
  {
    "familyId": "b777",
    "familyName": "波音 777",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b777-300er.jpg",
    "familyDesc": "波音 777 是世界上最大的双发宽体客机，远程巡航能力极强，是全球长途航线的主力之一。",
    "familyWiki": "https://baike.baidu.com/item/波音777",
    "id": "b777-300er",
    "name": "波音 777-300ER",
    "sub": "加长增程型",
    "firstFlight": "2003",
    "seats": "365 - 396",
    "range": "约 13,649 km",
    "cruise": "905 km/h",
    "engines": "两台 GE90-115B 涡扇",
    "wiki": "https://baike.baidu.com/item/波音777",
    "nameEn": "Boeing 777-300ER",
    "subEn": "Stretched Extended Range",
    "enginesEn": "Two GE90-115B turbofans",
    "familyNameEn": "Boeing 777",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Boeing 777 is the world's largest twin-engine wide-body airliner, with exceptional long-range cruise capability and a backbone of global long-haul routes."
  },
  {
    "familyId": "b787",
    "familyName": "波音 787 梦想客机",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b787-8.jpg",
    "familyDesc": "波音 787 大量采用复合材料与电传操纵，强调燃油效率与乘坐舒适性，是面向 21 世纪的远程宽体主力。",
    "familyWiki": "https://baike.baidu.com/item/波音787",
    "id": "b787-8",
    "name": "波音 787-8",
    "sub": "基本型",
    "firstFlight": "2009",
    "seats": "248",
    "range": "约 13,530 km",
    "cruise": "903 km/h",
    "engines": "两台 GEnx-1B / Trent 1000 涡扇",
    "wiki": "https://baike.baidu.com/item/波音787",
    "nameEn": "Boeing 787-8",
    "subEn": "Base version",
    "enginesEn": "Two GEnx-1B / Trent 1000 turbofans",
    "familyNameEn": "Boeing 787 Dreamliner",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Boeing 787 makes extensive use of composite materials and fly-by-wire controls, emphasizing fuel efficiency and passenger comfort as a 21st-century long-range wide-body mainstay."
  },
  {
    "familyId": "b787",
    "familyName": "波音 787 梦想客机",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b787-9.jpg",
    "familyDesc": "波音 787 大量采用复合材料与电传操纵，强调燃油效率与乘坐舒适性，是面向 21 世纪的远程宽体主力。",
    "familyWiki": "https://baike.baidu.com/item/波音787",
    "id": "b787-9",
    "name": "波音 787-9",
    "sub": "加长型",
    "firstFlight": "2013",
    "seats": "290",
    "range": "约 14,140 km",
    "cruise": "903 km/h",
    "engines": "两台 GEnx-1B / Trent 1000 涡扇",
    "wiki": "https://baike.baidu.com/item/波音787",
    "nameEn": "Boeing 787-9",
    "subEn": "Stretched version",
    "enginesEn": "Two GEnx-1B / Trent 1000 turbofans",
    "familyNameEn": "Boeing 787 Dreamliner",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Boeing 787 makes extensive use of composite materials and fly-by-wire controls, emphasizing fuel efficiency and passenger comfort as a 21st-century long-range wide-body mainstay."
  },
  {
    "familyId": "b787",
    "familyName": "波音 787 梦想客机",
    "manufacturer": "波音 (Boeing)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/b787-10.jpg",
    "familyDesc": "波音 787 大量采用复合材料与电传操纵，强调燃油效率与乘坐舒适性，是面向 21 世纪的远程宽体主力。",
    "familyWiki": "https://baike.baidu.com/item/波音787",
    "id": "b787-10",
    "name": "波音 787-10",
    "sub": "最大加长型",
    "firstFlight": "2017",
    "seats": "336",
    "range": "约 11,730 km",
    "cruise": "903 km/h",
    "engines": "两台 GEnx-1B 涡扇",
    "wiki": "https://baike.baidu.com/item/波音787",
    "nameEn": "Boeing 787-10",
    "subEn": "Largest stretched version",
    "enginesEn": "Two GEnx-1B turbofans",
    "familyNameEn": "Boeing 787 Dreamliner",
    "manufacturerEn": "Boeing",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Boeing 787 makes extensive use of composite materials and fly-by-wire controls, emphasizing fuel efficiency and passenger comfort as a 21st-century long-range wide-body mainstay."
  },
  {
    "familyId": "a320",
    "familyName": "空客 A320 系列",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "窄体客机",
    "image": "images/a318.jpg",
    "familyDesc": "空客 A320 系列是历史上最畅销的窄体客机，率先在民航引入电传操纵与侧杆，包含 A318/A319/A320/A321 等型号，并发展出 NEO（新型发动机选项）系列。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A320",
    "id": "a318",
    "name": "空客 A318",
    "sub": "A318-100（最小成员）",
    "firstFlight": "2002",
    "seats": "107 - 132",
    "range": "约 5,950 km",
    "cruise": "830 km/h",
    "engines": "两台 CFM56-5B / PW6000 涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A318",
    "nameEn": "Airbus A318",
    "subEn": "A318-100 (smallest member)",
    "enginesEn": "Two CFM56-5B / PW6000 turbofans",
    "familyNameEn": "Airbus A320 family",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Airbus A320 family is the best-selling narrow-body airliner in history, the first to introduce fly-by-wire and sidesticks in civil aviation, comprising the A318/A319/A320/A321 and the NEO (New Engine Option) variants."
  },
  {
    "familyId": "a320",
    "familyName": "空客 A320 系列",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "窄体客机",
    "image": "images/a319.jpg",
    "familyDesc": "空客 A320 系列是历史上最畅销的窄体客机，率先在民航引入电传操纵与侧杆，包含 A318/A319/A320/A321 等型号，并发展出 NEO（新型发动机选项）系列。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A320",
    "id": "a319",
    "name": "空客 A319",
    "sub": "A319-100 / A319neo",
    "firstFlight": "1995",
    "seats": "124 - 156",
    "range": "约 6,850 km",
    "cruise": "830 km/h",
    "engines": "两台 CFM56-5B / V2500 / LEAP-1A 涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A319",
    "nameEn": "Airbus A319",
    "subEn": "A319-100 / A319neo",
    "enginesEn": "Two CFM56-5B / V2500 / LEAP-1A turbofans",
    "familyNameEn": "Airbus A320 family",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Airbus A320 family is the best-selling narrow-body airliner in history, the first to introduce fly-by-wire and sidesticks in civil aviation, comprising the A318/A319/A320/A321 and the NEO (New Engine Option) variants."
  },
  {
    "familyId": "a320",
    "familyName": "空客 A320 系列",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "窄体客机",
    "image": "images/a320.jpg",
    "familyDesc": "空客 A320 系列是历史上最畅销的窄体客机，率先在民航引入电传操纵与侧杆，包含 A318/A319/A320/A321 等型号，并发展出 NEO（新型发动机选项）系列。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A320",
    "id": "a320",
    "name": "空客 A320",
    "sub": "A320-200 / A320neo",
    "firstFlight": "1987",
    "seats": "150 - 186",
    "range": "约 6,100 km",
    "cruise": "830 km/h",
    "engines": "两台 CFM56-5B / V2500 / LEAP-1A 涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A320",
    "nameEn": "Airbus A320",
    "subEn": "A320-200 / A320neo",
    "enginesEn": "Two CFM56-5B / V2500 / LEAP-1A turbofans",
    "familyNameEn": "Airbus A320 family",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Airbus A320 family is the best-selling narrow-body airliner in history, the first to introduce fly-by-wire and sidesticks in civil aviation, comprising the A318/A319/A320/A321 and the NEO (New Engine Option) variants."
  },
  {
    "familyId": "a320",
    "familyName": "空客 A320 系列",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "窄体客机",
    "image": "images/a321.jpg",
    "familyDesc": "空客 A320 系列是历史上最畅销的窄体客机，率先在民航引入电传操纵与侧杆，包含 A318/A319/A320/A321 等型号，并发展出 NEO（新型发动机选项）系列。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A320",
    "id": "a321",
    "name": "空客 A321",
    "sub": "A321-200 / A321neo / A321XLR",
    "firstFlight": "1993",
    "seats": "185 - 244",
    "range": "约 7,400 km（XLR 约 8,700 km）",
    "cruise": "830 km/h",
    "engines": "两台 CFM56-5B / V2500 / LEAP-1A 涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A321",
    "nameEn": "Airbus A321",
    "subEn": "A321-200 / A321neo / A321XLR",
    "enginesEn": "Two CFM56-5B / V2500 / LEAP-1A turbofans",
    "familyNameEn": "Airbus A320 family",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Airbus A320 family is the best-selling narrow-body airliner in history, the first to introduce fly-by-wire and sidesticks in civil aviation, comprising the A318/A319/A320/A321 and the NEO (New Engine Option) variants."
  },
  {
    "familyId": "a330",
    "familyName": "空客 A330",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "宽体客机",
    "image": "images/a330-200.jpg",
    "familyDesc": "空客 A330 是双发宽体客机，以高经济性与可靠性著称，是中远程航线的常见机型，并发展出 A330neo 系列。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A330",
    "id": "a330-200",
    "name": "空客 A330-200",
    "sub": "标准型",
    "firstFlight": "1997",
    "seats": "246 - 300",
    "range": "约 13,400 km",
    "cruise": "871 km/h",
    "engines": "两台 Trent 700 / CF6 / PW4000 涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A330",
    "nameEn": "Airbus A330-200",
    "subEn": "Standard version",
    "enginesEn": "Two Trent 700 / CF6 / PW4000 turbofans",
    "familyNameEn": "Airbus A330",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Airbus A330 is a twin-engine wide-body airliner known for its economy and reliability on medium- to long-haul routes, later developed into the A330neo family."
  },
  {
    "familyId": "a330",
    "familyName": "空客 A330",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "宽体客机",
    "image": "images/a330-300.jpg",
    "familyDesc": "空客 A330 是双发宽体客机，以高经济性与可靠性著称，是中远程航线的常见机型，并发展出 A330neo 系列。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A330",
    "id": "a330-300",
    "name": "空客 A330-300",
    "sub": "加长型",
    "firstFlight": "1993",
    "seats": "300 - 440",
    "range": "约 11,750 km",
    "cruise": "871 km/h",
    "engines": "两台 Trent 700 / CF6 / PW4000 涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A330",
    "nameEn": "Airbus A330-300",
    "subEn": "Stretched version",
    "enginesEn": "Two Trent 700 / CF6 / PW4000 turbofans",
    "familyNameEn": "Airbus A330",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Airbus A330 is a twin-engine wide-body airliner known for its economy and reliability on medium- to long-haul routes, later developed into the A330neo family."
  },
  {
    "familyId": "a330",
    "familyName": "空客 A330",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "宽体客机",
    "image": "images/a330neo.jpg",
    "familyDesc": "空客 A330 是双发宽体客机，以高经济性与可靠性著称，是中远程航线的常见机型，并发展出 A330neo 系列。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A330",
    "id": "a330neo",
    "name": "空客 A330neo",
    "sub": "A330-800 / A330-900",
    "firstFlight": "2014",
    "seats": "260 - 460",
    "range": "约 13,900 km",
    "cruise": "871 km/h",
    "engines": "两台 Rolls-Royce Trent 7000 涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A330",
    "nameEn": "Airbus A330neo",
    "subEn": "A330-800 / A330-900",
    "enginesEn": "Two Rolls-Royce Trent 7000 turbofans",
    "familyNameEn": "Airbus A330",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Airbus A330 is a twin-engine wide-body airliner known for its economy and reliability on medium- to long-haul routes, later developed into the A330neo family."
  },
  {
    "familyId": "a350",
    "familyName": "空客 A350",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "宽体客机",
    "image": "images/a350-900.jpg",
    "familyDesc": "空客 A350 是全新设计的宽体客机(XWB)，大量使用碳纤维复合材料，主打超远航程与低油耗。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A350",
    "id": "a350-900",
    "name": "空客 A350-900",
    "sub": "基本型",
    "firstFlight": "2013",
    "seats": "300 - 350",
    "range": "约 15,000 km",
    "cruise": "905 km/h",
    "engines": "两台 Rolls-Royce Trent XWB-84 涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A350",
    "nameEn": "Airbus A350-900",
    "subEn": "Base version",
    "enginesEn": "Two Rolls-Royce Trent XWB-84 turbofans",
    "familyNameEn": "Airbus A350",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Airbus A350 is an all-new wide-body airliner (XWB) using extensive carbon-fibre composites, built for ultra-long range and low fuel burn."
  },
  {
    "familyId": "a350",
    "familyName": "空客 A350",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "宽体客机",
    "image": "images/a350-1000.jpg",
    "familyDesc": "空客 A350 是全新设计的宽体客机(XWB)，大量使用碳纤维复合材料，主打超远航程与低油耗。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A350",
    "id": "a350-1000",
    "name": "空客 A350-1000",
    "sub": "加长型",
    "firstFlight": "2016",
    "seats": "350 - 410",
    "range": "约 16,100 km",
    "cruise": "905 km/h",
    "engines": "两台 Rolls-Royce Trent XWB-97 涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A350",
    "nameEn": "Airbus A350-1000",
    "subEn": "Stretched version",
    "enginesEn": "Two Rolls-Royce Trent XWB-97 turbofans",
    "familyNameEn": "Airbus A350",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Airbus A350 is an all-new wide-body airliner (XWB) using extensive carbon-fibre composites, built for ultra-long range and low fuel burn."
  },
  {
    "familyId": "a380",
    "familyName": "空客 A380",
    "manufacturer": "空客 (Airbus)",
    "country": "欧洲",
    "category": "宽体客机",
    "image": "images/a380-800.jpg",
    "familyDesc": "空客 A380 是世界上最大的客机，也是唯一的全双层喷气式客机，四发超宽体布局提供无与伦比的载客量。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A380",
    "id": "a380-800",
    "name": "空客 A380-800",
    "sub": "唯一量产型",
    "firstFlight": "2005",
    "seats": "525 - 853",
    "range": "约 15,200 km",
    "cruise": "920 km/h",
    "engines": "四台 GP7200 / Trent 900 涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A380",
    "nameEn": "Airbus A380-800",
    "subEn": "Only production variant",
    "enginesEn": "Four GP7200 / Trent 900 turbofans",
    "familyNameEn": "Airbus A380",
    "manufacturerEn": "Airbus",
    "countryEn": "Europe",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The Airbus A380 is the world's largest passenger aircraft and the only full double-deck jetliner, with a four-engine ultra-wide layout offering unmatched capacity."
  },
  {
    "familyId": "a220",
    "familyName": "空客 A220",
    "manufacturer": "空客 (Airbus)",
    "country": "加拿大",
    "category": "窄体客机",
    "image": "images/a220-100.jpg",
    "familyDesc": "空客 A220 最初由庞巴迪以 CSeries 名义研制，后被空客收购，专为 100-150 座市场设计，燃油效率出众。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A220",
    "id": "a220-100",
    "name": "空客 A220-100",
    "sub": "原 CS100",
    "firstFlight": "2013",
    "seats": "100 - 135",
    "range": "约 6,300 km",
    "cruise": "871 km/h",
    "engines": "两台 Pratt & Whitney PW1500G 齿轮传动涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A220",
    "nameEn": "Airbus A220-100",
    "subEn": "Formerly CS100",
    "enginesEn": "Two Pratt & Whitney PW1500G geared turbofans",
    "familyNameEn": "Airbus A220",
    "manufacturerEn": "Airbus",
    "countryEn": "Canada",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Airbus A220 was originally developed by Bombardier as the CSeries and later acquired by Airbus, designed for the 100-150 seat market with outstanding fuel efficiency."
  },
  {
    "familyId": "a220",
    "familyName": "空客 A220",
    "manufacturer": "空客 (Airbus)",
    "country": "加拿大",
    "category": "窄体客机",
    "image": "images/a220-300.jpg",
    "familyDesc": "空客 A220 最初由庞巴迪以 CSeries 名义研制，后被空客收购，专为 100-150 座市场设计，燃油效率出众。",
    "familyWiki": "https://baike.baidu.com/item/空中客车A220",
    "id": "a220-300",
    "name": "空客 A220-300",
    "sub": "原 CS300（加长型）",
    "firstFlight": "2015",
    "seats": "130 - 160",
    "range": "约 5,950 km",
    "cruise": "871 km/h",
    "engines": "两台 Pratt & Whitney PW1500G 齿轮传动涡扇",
    "wiki": "https://baike.baidu.com/item/空中客车A220",
    "nameEn": "Airbus A220-300",
    "subEn": "Formerly CS300 (stretched)",
    "enginesEn": "Two Pratt & Whitney PW1500G geared turbofans",
    "familyNameEn": "Airbus A220",
    "manufacturerEn": "Airbus",
    "countryEn": "Canada",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Airbus A220 was originally developed by Bombardier as the CSeries and later acquired by Airbus, designed for the 100-150 seat market with outstanding fuel efficiency."
  },
  {
    "familyId": "ejet",
    "familyName": "巴航工业 E-Jet",
    "manufacturer": "巴航工业 (Embraer)",
    "country": "巴西",
    "category": "支线客机",
    "image": "images/e170.jpg",
    "familyDesc": "巴航工业 E-Jet 系列是巴西航空工业公司研制的中小型支线喷气客机，兼顾经济性与舒适性。",
    "familyWiki": "https://baike.baidu.com/item/巴航工业E系列",
    "id": "e170",
    "name": "巴航 E170",
    "sub": "最小成员",
    "firstFlight": "2002",
    "seats": "66 - 80",
    "range": "约 3,890 km",
    "cruise": "850 km/h",
    "engines": "两台 CF34-8E 涡扇",
    "wiki": "https://baike.baidu.com/item/巴航工业E系列",
    "nameEn": "Embraer E170",
    "subEn": "Smallest member",
    "enginesEn": "Two CF34-8E turbofans",
    "familyNameEn": "Embraer E-Jet",
    "manufacturerEn": "Embraer",
    "countryEn": "Brazil",
    "categoryEn": "Regional jet",
    "familyDescEn": "The Embraer E-Jet family is a range of small-to-medium regional jets from Embraer, balancing economy and comfort."
  },
  {
    "familyId": "ejet",
    "familyName": "巴航工业 E-Jet",
    "manufacturer": "巴航工业 (Embraer)",
    "country": "巴西",
    "category": "支线客机",
    "image": "images/e190.jpg",
    "familyDesc": "巴航工业 E-Jet 系列是巴西航空工业公司研制的中小型支线喷气客机，兼顾经济性与舒适性。",
    "familyWiki": "https://baike.baidu.com/item/巴航工业E系列",
    "id": "e190",
    "name": "巴航 E190",
    "sub": "最受欢迎型号",
    "firstFlight": "2004",
    "seats": "96 - 114",
    "range": "约 4,537 km",
    "cruise": "850 km/h",
    "engines": "两台 CF34-10E 涡扇",
    "wiki": "https://baike.baidu.com/item/巴航工业E系列",
    "nameEn": "Embraer E190",
    "subEn": "Most popular variant",
    "enginesEn": "Two CF34-10E turbofans",
    "familyNameEn": "Embraer E-Jet",
    "manufacturerEn": "Embraer",
    "countryEn": "Brazil",
    "categoryEn": "Regional jet",
    "familyDescEn": "The Embraer E-Jet family is a range of small-to-medium regional jets from Embraer, balancing economy and comfort."
  },
  {
    "familyId": "ejet",
    "familyName": "巴航工业 E-Jet",
    "manufacturer": "巴航工业 (Embraer)",
    "country": "巴西",
    "category": "支线客机",
    "image": "images/e195e2.jpg",
    "familyDesc": "巴航工业 E-Jet 系列是巴西航空工业公司研制的中小型支线喷气客机，兼顾经济性与舒适性。",
    "familyWiki": "https://baike.baidu.com/item/巴航工业E系列",
    "id": "e195e2",
    "name": "巴航 E195-E2",
    "sub": "E2 新一代",
    "firstFlight": "2016",
    "seats": "120 - 146",
    "range": "约 4,815 km",
    "cruise": "850 km/h",
    "engines": "两台 Pratt & Whitney PW1900G 齿轮传动涡扇",
    "wiki": "https://baike.baidu.com/item/巴航工业E-Jet_E2",
    "nameEn": "Embraer E195-E2",
    "subEn": "New-generation E2",
    "enginesEn": "Two Pratt & Whitney PW1900G geared turbofans",
    "familyNameEn": "Embraer E-Jet",
    "manufacturerEn": "Embraer",
    "countryEn": "Brazil",
    "categoryEn": "Regional jet",
    "familyDescEn": "The Embraer E-Jet family is a range of small-to-medium regional jets from Embraer, balancing economy and comfort."
  },
  {
    "familyId": "crj",
    "familyName": "庞巴迪 CRJ",
    "manufacturer": "庞巴迪 (Bombardier)",
    "country": "加拿大",
    "category": "支线客机",
    "image": "images/crj700.jpg",
    "familyDesc": "庞巴迪 CRJ 系列是全球最成功的支线喷气客机之一，后由三菱重工收购，主要服务于低密度支线航线。",
    "familyWiki": "https://baike.baidu.com/item/庞巴迪CRJ",
    "id": "crj700",
    "name": "庞巴迪 CRJ700",
    "sub": "标准型",
    "firstFlight": "1999",
    "seats": "66 - 78",
    "range": "约 2,350 km",
    "cruise": "860 km/h",
    "engines": "两台 CF34-8C 涡扇",
    "wiki": "https://baike.baidu.com/item/庞巴迪CRJ",
    "nameEn": "Bombardier CRJ700",
    "subEn": "Standard version",
    "enginesEn": "Two CF34-8C turbofans",
    "familyNameEn": "Bombardier CRJ",
    "manufacturerEn": "Bombardier",
    "countryEn": "Canada",
    "categoryEn": "Regional jet",
    "familyDescEn": "The Bombardier CRJ series is among the most successful regional jets ever, later acquired by Mitsubishi Heavy Industries, serving low-density regional routes."
  },
  {
    "familyId": "crj",
    "familyName": "庞巴迪 CRJ",
    "manufacturer": "庞巴迪 (Bombardier)",
    "country": "加拿大",
    "category": "支线客机",
    "image": "images/crj900.jpg",
    "familyDesc": "庞巴迪 CRJ 系列是全球最成功的支线喷气客机之一，后由三菱重工收购，主要服务于低密度支线航线。",
    "familyWiki": "https://baike.baidu.com/item/庞巴迪CRJ",
    "id": "crj900",
    "name": "庞巴迪 CRJ900",
    "sub": "加长型",
    "firstFlight": "2001",
    "seats": "72 - 100",
    "range": "约 2,950 km",
    "cruise": "860 km/h",
    "engines": "两台 CF34-8C5 涡扇",
    "wiki": "https://baike.baidu.com/item/庞巴迪CRJ",
    "nameEn": "Bombardier CRJ900",
    "subEn": "Stretched version",
    "enginesEn": "Two CF34-8C5 turbofans",
    "familyNameEn": "Bombardier CRJ",
    "manufacturerEn": "Bombardier",
    "countryEn": "Canada",
    "categoryEn": "Regional jet",
    "familyDescEn": "The Bombardier CRJ series is among the most successful regional jets ever, later acquired by Mitsubishi Heavy Industries, serving low-density regional routes."
  },
  {
    "familyId": "crj",
    "familyName": "庞巴迪 CRJ",
    "manufacturer": "庞巴迪 (Bombardier)",
    "country": "加拿大",
    "category": "支线客机",
    "image": "images/crj1000.jpg",
    "familyDesc": "庞巴迪 CRJ 系列是全球最成功的支线喷气客机之一，后由三菱重工收购，主要服务于低密度支线航线。",
    "familyWiki": "https://baike.baidu.com/item/庞巴迪CRJ",
    "id": "crj1000",
    "name": "庞巴迪 CRJ1000",
    "sub": "最大加长型",
    "firstFlight": "2009",
    "seats": "97 - 104",
    "range": "约 2,780 km",
    "cruise": "860 km/h",
    "engines": "两台 CF34-8C5 涡扇",
    "wiki": "https://baike.baidu.com/item/庞巴迪CRJ",
    "nameEn": "Bombardier CRJ1000",
    "subEn": "Largest stretched version",
    "enginesEn": "Two CF34-8C5 turbofans",
    "familyNameEn": "Bombardier CRJ",
    "manufacturerEn": "Bombardier",
    "countryEn": "Canada",
    "categoryEn": "Regional jet",
    "familyDescEn": "The Bombardier CRJ series is among the most successful regional jets ever, later acquired by Mitsubishi Heavy Industries, serving low-density regional routes."
  },
  {
    "familyId": "atr72",
    "familyName": "ATR 72",
    "manufacturer": "ATR",
    "country": "法国 / 意大利",
    "category": "涡桨客机",
    "image": "images/atr72-600.jpg",
    "familyDesc": "ATR 72 是法国与意大利合资公司 ATR 研制的双发涡桨支线客机，以低油耗适合短途低密度航线。",
    "familyWiki": "https://baike.baidu.com/item/ATR72",
    "id": "atr72-600",
    "name": "ATR 72-600",
    "sub": "最新量产型",
    "firstFlight": "2009",
    "seats": "68 - 78",
    "range": "约 1,528 km",
    "cruise": "509 km/h",
    "engines": "两台 PW127M 涡桨发动机",
    "wiki": "https://baike.baidu.com/item/ATR72",
    "nameEn": "ATR 72-600",
    "subEn": "Latest production variant",
    "enginesEn": "Two PW127M turboprop engines",
    "familyNameEn": "ATR 72",
    "manufacturerEn": "ATR",
    "countryEn": "France / Italy",
    "categoryEn": "Turboprop airliner",
    "familyDescEn": "The ATR 72 is a twin-engine turboprop regional airliner from the French-Italian joint venture ATR, fuel-efficient for short, low-density routes."
  },
  {
    "familyId": "c919",
    "familyName": "中国商飞 C919",
    "manufacturer": "中国商飞 (Comac)",
    "country": "中国",
    "category": "窄体客机",
    "image": "images/c919.jpg",
    "familyDesc": "C919 是中国商飞研制的中程窄体客机，于 2008 年立项，对标空客 A320 与波音 737，是中国首款按国际适航标准研制的干线客机。",
    "familyWiki": "https://baike.baidu.com/item/C919",
    "id": "c919",
    "name": "中国商飞 C919",
    "sub": "标准型",
    "firstFlight": "2017",
    "seats": "158 - 192",
    "range": "约 5,555 km",
    "cruise": "834 km/h",
    "engines": "两台 LEAP-1C 涡扇发动机",
    "wiki": "https://baike.baidu.com/item/C919",
    "nameEn": "Comac C919",
    "subEn": "Standard version",
    "enginesEn": "Two LEAP-1C turbofan engines",
    "familyNameEn": "Comac C919",
    "manufacturerEn": "Comac",
    "countryEn": "China",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The Comac C919 is a medium-range narrow-body airliner developed by Comac, launched in 2008 to compete with the Airbus A320 and Boeing 737, and China's first trunk airliner built to international airworthiness standards."
  },
  {
    "familyId": "md",
    "familyName": "麦道 MD 系列",
    "manufacturer": "麦道 (McDonnell Douglas)",
    "country": "美国",
    "category": "窄体客机",
    "image": "images/md80.jpg",
    "familyDesc": "麦道 MD 系列是基于 DC-9 发展的单通道客机，采用尾吊双发布局，曾是上世纪 80-90 年代美国国内航线的主力之一。",
    "familyWiki": "https://baike.baidu.com/item/麦克唐纳-道格拉斯MD-80",
    "id": "md80",
    "name": "麦道 MD-80",
    "sub": "MD-82 / MD-83 等",
    "firstFlight": "1979",
    "seats": "130 - 172",
    "range": "约 3,600 km",
    "cruise": "811 km/h",
    "engines": "两台 Pratt & Whitney JT8D-200 涡扇",
    "wiki": "https://baike.baidu.com/item/麦克唐纳-道格拉斯MD-80",
    "nameEn": "McDonnell Douglas MD-80",
    "subEn": "MD-82 / MD-83 etc.",
    "enginesEn": "Two Pratt & Whitney JT8D-200 turbofans",
    "familyNameEn": "McDonnell Douglas MD series",
    "manufacturerEn": "McDonnell Douglas",
    "countryEn": "USA",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The McDonnell Douglas MD series is a single-aisle airliner developed from the DC-9 with a rear-mounted twin-engine layout, a mainstay of US domestic routes in the 1980s-90s."
  },
  {
    "familyId": "md",
    "familyName": "麦道 MD 系列",
    "manufacturer": "麦道 (McDonnell Douglas)",
    "country": "美国",
    "category": "窄体客机",
    "image": "images/md90.jpg",
    "familyDesc": "麦道 MD 系列是基于 DC-9 发展的单通道客机，采用尾吊双发布局，曾是上世纪 80-90 年代美国国内航线的主力之一。",
    "familyWiki": "https://baike.baidu.com/item/麦克唐纳-道格拉斯MD-80",
    "id": "md90",
    "name": "麦道 MD-90",
    "sub": "放大型",
    "firstFlight": "1993",
    "seats": "153 - 172",
    "range": "约 3,860 km",
    "cruise": "811 km/h",
    "engines": "两台 IAE V2525-D5 涡扇",
    "wiki": "https://baike.baidu.com/item/麦克唐纳-道格拉斯MD-90",
    "nameEn": "McDonnell Douglas MD-90",
    "subEn": "Enlarged version",
    "enginesEn": "Two IAE V2525-D5 turbofans",
    "familyNameEn": "McDonnell Douglas MD series",
    "manufacturerEn": "McDonnell Douglas",
    "countryEn": "USA",
    "categoryEn": "Narrow-body airliner",
    "familyDescEn": "The McDonnell Douglas MD series is a single-aisle airliner developed from the DC-9 with a rear-mounted twin-engine layout, a mainstay of US domestic routes in the 1980s-90s."
  },
  {
    "familyId": "mdd-wide",
    "familyName": "麦道 DC-10 / MD-11",
    "manufacturer": "麦道 (McDonnell Douglas)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/dc10.jpg",
    "familyDesc": "麦道 DC-10 与 MD-11 是三发宽体客机，采用尾部第三发动机布局，曾广泛服务于跨洋航线与货运市场。DC-10 于 1970 年代首飞，MD-11 为其加长改进型，航程与燃油效率大幅提升。中国东方航空曾运营 MD-11 客货型号。",
    "familyWiki": "https://baike.baidu.com/item/DC-10",
    "id": "dc10",
    "name": "麦道 DC-10",
    "sub": "DC-10-10 / -30 / -40",
    "firstFlight": "1970",
    "seats": "250 - 380",
    "range": "约 9,600 - 12,000 km",
    "cruise": "908 km/h",
    "engines": "三台 GE CF6 / PW JT9D / RR RB211 涡扇",
    "wiki": "https://baike.baidu.com/item/DC-10",
    "nameEn": "McDonnell Douglas DC-10",
    "subEn": "DC-10-10 / -30 / -40",
    "enginesEn": "Three GE CF6 / PW JT9D / RR RB211 turbofans",
    "familyNameEn": "McDonnell Douglas DC-10 / MD-11",
    "manufacturerEn": "McDonnell Douglas",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The McDonnell Douglas DC-10 and MD-11 are wide-body trijet airliners featuring a tail-mounted third engine. They served transoceanic routes and cargo markets worldwide. The DC-10 first flew in the 1970s; the MD-11 is a stretched derivative with significantly improved range and fuel efficiency. China Eastern Airlines operated both passenger and freighter MD-11s."
  },
  {
    "familyId": "mdd-wide",
    "familyName": "麦道 DC-10 / MD-11",
    "manufacturer": "麦道 (McDonnell Douglas)",
    "country": "美国",
    "category": "宽体客机",
    "image": "images/md11.jpg",
    "familyDesc": "麦道 DC-10 与 MD-11 是三发宽体客机，采用尾部第三发动机布局，曾广泛服务于跨洋航线与货运市场。DC-10 于 1970 年代首飞，MD-11 为其加长改进型，航程与燃油效率大幅提升。中国东方航空曾运营 MD-11 客货型号。",
    "familyWiki": "https://baike.baidu.com/item/DC-10",
    "id": "md11",
    "name": "麦道 MD-11",
    "sub": "DC-10 加长改进型",
    "firstFlight": "1990",
    "seats": "285 - 410",
    "range": "约 12,700 km",
    "cruise": "945 km/h",
    "engines": "三台 GE CF6-80C2 / PW4000 涡扇",
    "wiki": "https://baike.baidu.com/item/MD-11",
    "nameEn": "McDonnell Douglas MD-11",
    "subEn": "Stretched DC-10 derivative",
    "enginesEn": "Three GE CF6-80C2 / PW4000 turbofans",
    "familyNameEn": "McDonnell Douglas DC-10 / MD-11",
    "manufacturerEn": "McDonnell Douglas",
    "countryEn": "USA",
    "categoryEn": "Wide-body airliner",
    "familyDescEn": "The McDonnell Douglas DC-10 and MD-11 are wide-body trijet airliners featuring a tail-mounted third engine. They served transoceanic routes and cargo markets worldwide. The DC-10 first flew in the 1970s; the MD-11 is a stretched derivative with significantly improved range and fuel efficiency. China Eastern Airlines operated both passenger and freighter MD-11s."
  },
  {
    "familyId": "c909",
    "familyName": "中国商飞 C909",
    "manufacturer": "中国商飞 (Comac)",
    "country": "中国",
    "category": "支线客机",
    "image": "images/c909.jpg",
    "familyDesc": "C909 是中国商飞研制的支线喷气客机，前身为 ARJ21（21 世纪新一代支线飞机）。采用尾吊双发布局，2008 年首飞，是中国首款拥有自主知识产权的涡扇支线客机；2024 年起以 C909 品牌运营。",
    "familyWiki": "https://baike.baidu.com/item/ARJ21",
    "id": "c909-700",
    "name": "中国商飞 C909（标准型）",
    "sub": "ARJ21-700",
    "firstFlight": "2008",
    "seats": "78 - 105",
    "range": "约 3,700 km",
    "cruise": "830 km/h",
    "engines": "两台 CF34-10A 涡扇发动机",
    "wiki": "https://baike.baidu.com/item/ARJ21",
    "nameEn": "Comac C909 (standard)",
    "subEn": "ARJ21-700",
    "enginesEn": "Two CF34-10A turbofan engines",
    "familyNameEn": "Comac C909",
    "manufacturerEn": "Comac",
    "countryEn": "China",
    "categoryEn": "Regional jet",
    "familyDescEn": "The Comac C909 is a regional jet airliner developed by Comac, formerly known as the ARJ21 (Advanced Regional Jet). With a rear-mounted twin-engine layout, it first flew in 2008 and is China's first indigenously developed turbofan regional airliner; it has been marketed under the C909 brand since 2024."
  },
  {
    "familyId": "c909",
    "familyName": "中国商飞 C909",
    "manufacturer": "中国商飞 (Comac)",
    "country": "中国",
    "category": "支线客机",
    "image": "images/c909.jpg",
    "familyDesc": "C909 是中国商飞研制的支线喷气客机，前身为 ARJ21（21 世纪新一代支线飞机）。采用尾吊双发布局，2008 年首飞，是中国首款拥有自主知识产权的涡扇支线客机；2024 年起以 C909 品牌运营。",
    "familyWiki": "https://baike.baidu.com/item/ARJ21",
    "id": "c909-900",
    "name": "中国商飞 C909（加长型）",
    "sub": "ARJ21-900（规划中）",
    "firstFlight": "—",
    "seats": "约 105 - 115",
    "range": "约 3,300 km",
    "cruise": "830 km/h",
    "engines": "两台 CF34-10A 涡扇发动机",
    "wiki": "https://baike.baidu.com/item/ARJ21",
    "nameEn": "Comac C909 (stretched)",
    "subEn": "ARJ21-900 (planned)",
    "enginesEn": "Two CF34-10A turbofan engines",
    "familyNameEn": "Comac C909",
    "manufacturerEn": "Comac",
    "countryEn": "China",
    "categoryEn": "Regional jet",
    "familyDescEn": "The Comac C909 is a regional jet airliner developed by Comac, formerly known as the ARJ21 (Advanced Regional Jet). With a rear-mounted twin-engine layout, it first flew in 2008 and is China's first indigenously developed turbofan regional airliner; it has been marketed under the C909 brand since 2024."
  }
];

if (typeof module !== "undefined" && module.exports) { module.exports = { FAMILIES, AIRCRAFT }; }
// 浏览器环境：显式挂到 window，供 app.js 访问
if (typeof window !== "undefined") { window.FAMILIES = FAMILIES; window.AIRCRAFT = AIRCRAFT; }
